apiVersion: skaffold/v2alpha4
kind: Config
# Enforce SKaffold to use Jib
build: 
# Generated artifact
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VER}}"
  artifacts:
    # - image: saturn203/simple-api
    # - image: saturn203/simple-api
    - image: simple
     
# Use jib
      jib: 
        args: 
        - -DskipTests
       

# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/simple.yaml

profiles:          
  - name: dev
    build:      
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.VER}}"
      artifacts:
        # - image: 862672955125.dkr.ecr.ap-northeast-2.amazonaws.com/edin-api
        # - image: saturn203/edin-api
        - image: asia.gcr.io/io203-101/simple
          jib: 
            args: 
            - -DskipTests 
            
  